version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: areal-hr-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: ext-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: